name: 'Deploy API'
description: 'Deploy da API no API Manager'

inputs:
  api-name:
    description: 'Nome da API'
    required: true
  api-version:
    description: 'Versão da API'
    required: true
  environment:
    description: 'Ambiente (dev, qas, prod)'
    required: true
  anypoint-client-id:
    description: 'Anypoint Client ID'
    required: true
  anypoint-client-secret:
    description: 'Anypoint Client Secret'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Verificar se API existe
      shell: bash
      run: |
        ${{ github.action_path }}/../../../scripts/check-api-exists.sh \
          "${{ inputs.api-name }}" \
          "${{ inputs.environment }}"
      env:
        ANYPOINT_CLIENT_ID: ${{ inputs.anypoint-client-id }}
        ANYPOINT_CLIENT_SECRET: ${{ inputs.anypoint-client-secret }}
    
    - name: Deploy API
      shell: bash
      run: |
        ${{ github.action_path }}/../../../scripts/deploy-api.sh \
          "${{ inputs.api-name }}" \
          "${{ inputs.api-version }}" \
          "${{ inputs.environment }}" \
          "$(cat /tmp/api-exists.txt 2>/dev/null || echo 'false')"
      env:
        ANYPOINT_CLIENT_ID: ${{ inputs.anypoint-client-id }}
        ANYPOINT_CLIENT_SECRET: ${{ inputs.anypoint-client-secret }}

