name: 'Get Gateway Configuration'
description: 'Obtém a configuração do gateway (ID, versão e label) baseado no ambiente, cluster e tipo de exposição'

inputs:
  environment:
    description: 'Ambiente (dev, qas, prod)'
    required: true
  destination-cluster:
    description: 'Cluster de destino (aws-rosa, on-premise, pix, pj)'
    required: true
  is-public:
    description: 'Se a API é pública (true/false)'
    required: true
  client-id:
    description: 'Anypoint Client ID'
    required: true
  client-secret:
    description: 'Anypoint Client Secret'
    required: true
  organization-id:
    description: 'Organization ID'
    required: true
  asset-version:
    description: 'Versão do asset no Exchange'
    required: true

outputs:
  gateway-id:
    description: 'ID do gateway Flex'
    value: ${{ steps.get-config.outputs.gateway_id }}
  gateway-version:
    description: 'Versão do gateway Flex'
    value: ${{ steps.get-config.outputs.gateway_version }}
  gateway-label:
    description: 'Label do gateway (public/private)'
    value: ${{ steps.get-config.outputs.gateway_label }}
  gateway-type:
    description: 'Tipo do gateway (dmz/back)'
    value: ${{ steps.get-config.outputs.gateway_type }}

runs:
  using: 'composite'
  steps:
    - name: Instalar dependências
      shell: bash
      run: |
        if ! command -v jq &> /dev/null; then
          sudo apt-get update && sudo apt-get install -y jq
        fi
    
    - name: Executar script de configuração
      shell: bash
      env:
        ANYPOINT_CLIENT_ID: ${{ inputs.client-id }}
        ANYPOINT_CLIENT_SECRET: ${{ inputs.client-secret }}
      run: |
        bash ${{ github.action_path }}/../../../scripts/get-gateway-config.sh \
          "${{ inputs.environment }}" \
          "${{ inputs.destination-cluster }}" \
          "${{ inputs.is-public }}" \
          "${{ inputs.organization-id }}" \
          "${{ inputs.asset-version }}"
    
    - name: Ler outputs do script
      id: get-config
      shell: bash
      run: |
        GATEWAY_ID=$(cat /tmp/gateway-id.txt)
        GATEWAY_VERSION=$(cat /tmp/gateway-version.txt)
        GATEWAY_LABEL=$(cat /tmp/gateway-label.txt)
        GATEWAY_TYPE=$(cat /tmp/gateway-type.txt)
        
        echo "gateway_id=$GATEWAY_ID" >> $GITHUB_OUTPUT
        echo "gateway_version=$GATEWAY_VERSION" >> $GITHUB_OUTPUT
        echo "gateway_label=$GATEWAY_LABEL" >> $GITHUB_OUTPUT
        echo "gateway_type=$GATEWAY_TYPE" >> $GITHUB_OUTPUT

